<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\RacingUpdateProcessor.FileHandlers\RacingUpdateProcessor.FileHandlers.csproj" />
    <ProjectReference Include="..\RacingUpdateProcessor.Mapping\RacingUpdateProcessor.Mappers.csproj" />
    <ProjectReference Include="..\RacingUpdateProcessor.Notifications\RacingUpdateProcessor.Notifications.csproj" />
  </ItemGroup>

</Project>
